spring:
  application:
    name: productsapi
  datasource:
    url: jdbc:h2:mem:productsAPI
    username: cs1998
    password: 2005
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
